common/models/Article.php
<?php

namespace common\models;

use yii\db\ActiveRecord;
use yii\helpers\Url;

class Article extends ActiveRecord
{
    public static function tableName()
    {
        return '{{ArticlePublisher}}';
    }

    public function saveArticle($publisherId, $content, $image)
    {
        $this->savePublisher($publisherId);
        $this->saveContent($content);
        $this->saveImage($image);
    }

    public function delete()
    {
        $this->deleteArticle();
        $this->deleteReply();
    }

    public function getReply()
    {
        return $this->hasMany(Reply::className(), ['article_id' => 'article_id'])->all();
    }

    public function getPublisher()
    {
        return $this->hasOne(User::className(), ['id' => 'publisher_id'])->one()->username;
    }

    public function getContent()
    {
        return $this->hasOne(ArticleContent::className(), ['article_id' => 'article_id'])->one()->content;
    }

    public function getImage()
    {
        return $this->hasMany(ArticleImage::className(), ['article_id' => 'article_id'])->all();
    }

    private function savePublisher($publisherId)
    {
        $this->publisher_id = $publisherId;
        $this->save();
    }

    private function saveContent($content)
    {
        $tmp = new ArticleContent;
        $tmp->article_id = $this->article_id;
        $tmp->content = $content;
        $tmp->save();
    }

    private function saveImage($image)
    {
        if (!empty($image)) {
            foreach ($image as $item) {
                $tmp = new ArticleImage;
                $tmp->article_id = $this->article_id;
                $tmp->image = $this->uploadImg($item);
                $tmp->save();
            }
        }
    }

    private function uploadImg($file)
    {
        $rand = md5(uniqid(rand(), true));
        $file->saveAs(URl::to("@app/web/uploads/") . $rand . '.' . $file->extension);
        return "http://" . $_SERVER['HTTP_HOST'] . Url::base() . '/uploads/' . $rand . '.' . $file->extension;
    }

    private function deleteArticle()
    {
        parent::delete();
        ArticleContent::findOne($this->article_id)->delete();
        if (!is_null($img = ArticleImage::findOne(['article_id' => $this->article_id]))) {
            $img->delete();
        }
    }

    private function deleteReply()
    {
        foreach ($this->reply as $item) {
            $item->delete();
        }
    }
}

common/models/Reply.php
<?php

namespace common\models;

use yii\db\ActiveRecord;

class Reply extends ActiveRecord
{
    public static function tableName()
    {
        return '{{ReplyArticle}}';
    }

    public function saveReply($articleId, $replierId, $replyText)
    {
        $this->saveArticle($articleId);
        $this->saveReplier($replierId);
        $this->saveReplyText($replyText);
    }

    public function delete()
    {
        parent::delete();
        Replier::findOne($this->reply_id)->delete();
        ReplyText::findOne($this->reply_id)->delete();
    }

    public function getReplier()
    {
        return $this->hasOne(Replier::className(), ['reply_id' => 'reply_id'])->one()
            ->hasOne(User::className(), ['id' => 'replier_id'])->one()->username;
    }

    public function getReplyText()
    {
        return $this->hasOne(ReplyText::className(), ['reply_id' => 'reply_id'])->one()->text;
    }

    private function saveArticle($articleId)
    {
        $this->article_id = $articleId;
        $this->save();
    }

    private function saveReplier($replierId)
    {
        $tmp = new Replier;
        $tmp->reply_id = $this->reply_id;
        $tmp->replier_id = $replierId;
        $tmp->save();
    }

    private function saveReplyText($replyText)
    {
        $tmp = new ReplyText;
        $tmp->reply_id = $this->reply_id;
        $tmp->text = $replyText;
        $tmp->save();
    }
}

backend/controllers/SiteController.php
<?php

namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use common\models\Article;
use app\models\BoardForm;
use yii\data\Pagination;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error', 'delete', 'test'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        if (Yii::$app->user->isGuest) {

            $model = new LoginForm();
            if ($model->load(Yii::$app->request->post()) && $model->login()) {
                return $this->goBack();
            } else {
                $model->password = '';

                return $this->render('login', [
                    'model' => $model,
                ]);
            }
        } else {
            $model = new BoardForm();

            $query = Article::find();

            $pagination = new Pagination([
                'defaultPageSize' => 2,
                'totalCount' => $query->count(),
            ]);

            $result = $query->orderBy('article_id')
                ->offset($pagination->offset)
                ->limit($pagination->limit)
                ->all();

            if ($model->load(Yii::$app->request->post())) {
                //return $this->refresh();
                $model->del();
                return $this->refresh();
            } else {
                return $this->render("delete", [
                    'model' => $model,
                    'result' => $result,
                    'pagination' => $pagination,
                ]);
            }
        }
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionTest()
    {
        $model = new BoardForm();
        return $this->render('test');
    }
}

frontend/controllers/SiteController.php
<?php

namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use common\models\Article;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use app\models\BoardForm;
use app\models\PublishForm;
use yii\data\Pagination;
use yii\web\UploadedFile;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        if (Yii::$app->user->isGuest) {

            $model = new LoginForm();
            if ($model->load(Yii::$app->request->post()) && $model->login()) {
                return $this->goBack();
            } else {
                $model->password = '';

                return $this->render('login', [
                    'model' => $model,
                ]);
            }
        } else {
            $model = new PublishForm();
            return $this->render('publish', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success',
                    'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error',
                    'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    public function actionBoard()
    {
        if (!Yii::$app->user->isGuest) {
            $model = new BoardForm();
            $query = Article::find();

            $pagination = new Pagination([
                'defaultPageSize' => 2,
                'totalCount' => $query->count(),
            ]);

            $result = $query->orderBy('article_id')
                ->offset($pagination->offset)
                ->limit($pagination->limit)
                ->all();


            if ($model->load(Yii::$app->request->post())) {
                $model->reply();
                return $this->refresh();
            } else {
                return $this->render("reply", [
                    'model' => $model,
                    'result' => $result,
                    'pagination' => $pagination,
                ]);
            }
        } else {
            return $this->goHome();
        }
    }

    public function actionPublish()
    {
        //var_dump($_SERVER['HTTP_HOST'].Url::base());die();
        //var_dump(Yii::$app->urlManager->createUrl('../../'));die();
        if (!Yii::$app->user->isGuest) {
            $model = new PublishForm();
            if ($model->load(Yii::$app->request->post())) {
                $model->img = UploadedFile::getInstances($model, 'img');
                $model->publish();
                return $this->refresh();
            } else {
                return $this->render("publish", [
                    'model' => $model,
                ]);
            }
        } else {
            return $this->goHome();
        }
    }
}

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>This is the About page. You may modify the following file to customize its content:</p>

    <code><?= __FILE__ ?></code>
</div>

frontend/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */

/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

            <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

            <?= $form->field($model, 'email') ?>

            <?= $form->field($model, 'subject') ?>

            <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

            <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
            ]) ?>

            <div class="form-group">
                <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>

</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */

/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Congratulations!</h1>

        <p class="lead">You have successfully created your Yii-powered application.</p>

        <p><a class="btn btn-lg btn-success" href="http://www.yiiframework.com">Get started with Yii</a></p>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
                    et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
                    aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum
                    dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/doc/">Yii Documentation &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
                    et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
                    aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum
                    dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/forum/">Yii Forum &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
                    et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
                    aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum
                    dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/extensions/">Yii Extensions &raquo;</a>
                </p>
            </div>
        </div>

    </div>
</div>

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */

/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = '登入';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>請輸入帳號密碼:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin([
                'id' => 'login-form',
                //'fieldConfig' => [
                //    'inputOptions' => ['autocomplete' => 'off'],
                //],
            ]); ?>

            <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

            <?= $form->field($model, 'password')->passwordInput() ?>

            <?= $form->field($model, 'rememberMe')->checkbox() ?>

            <div style="color:#999;margin:1em 0">
                If you forgot your password you can <?= Html::a('reset it', ['site/request-password-reset']) ?>.
            </div>

            <div class="form-group">
                <?= Html::submitButton('登入', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/publish.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;

$this->title = '發文';
$this->params['breadcrumbs'][] = $this->title;
?>

<head>
    <link rel="stylesheet" href="<?php echo Url::to('@web/css/content.css') ?>">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
</head>
<body>

<?php $form = ActiveForm::begin([
    'action' => ['publish'],
    'fieldConfig' => [
        'template' => "<div>{input}<div>{error}</div></div>",
    ],
]); ?>
<p>在下方輸入文字發文：</p>
<?= $form->field($model, "content")->textarea(["rows" => 10]) ?>
<?= $form->field($model, 'img[]', [
    'template' => '{error}{label}{input}',
    'inputOptions' => ['id' => 'imgBtn'],
])->fileInput([
    'class' => 'file-upload',
    'multiple' => 'true',
])->label("上傳圖片", ['class' => 'btn btn-info',]) ?>
<?= Html::submitButton('發文', [
    'class' => 'btn btn-primary',
]) ?>
<div id="show">

</div>
<!--
<?= Html::tag('p', '', ['class' => 'previewText']) ?>
<?= Html::img("", ['class' => 'preview']) ?>
-->
<?php ActiveForm::end(); ?>

<script>
    function readURL(input) {
        $('#show').empty();
        for (let i = 0; i < input.files.length; i++) {
            let reader = new FileReader();

            reader.onload = function (e) {
                $('#show').append('<p class="previewText">預覽圖: ' + input.files[i].name + '</p>');
                $('#show').append('<img src= "' + e.target.result + '"/>');
            };
            console.log(input.files[i]);
            reader.readAsDataURL(input.files[i]);
        }

    }

    $("#imgBtn").change(function () {
        readURL(this);
        //console.log(this.files.length);
    });
</script>

</body>

frontend/views/site/reply.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\LinkPager;
use yii\bootstrap\ActiveForm;

$this->title = '貼文版';
$this->params['breadcrumbs'][] = $this->title;
?>

<head>
    <link rel="stylesheet" href="<?php echo Url::to('@web/css/content.css') ?>">
</head>
<body>

<?php foreach ($result as $item): ?>
    <?php $form = ActiveForm::begin([
        'id' => 'form' . $item->article_id,
        'fieldConfig' => [
            'template' => "{input}",
            'inputOptions' => ['autocomplete' => 'off'],
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>
    <div class='article'>
        <?= Html::encode("#$item->article_id") ?>
        <br><br>
        <?= Html::encode("$item->publisher :") ?>

        <div class='content'>
            <?= Html::encode("$item->content") ?>
        </div>

        <?php foreach ($item->image as $img): ?>
            <?= Html::a(Html::img($img->image, ['class' => 'img']), $img->image, ['target' => '_blank']); ?>
        <?php endforeach; ?>

        <?php foreach ($item->getReply() as $detail): ?>
            <div class="reply">
                <?= Html::encode("$detail->replier : $detail->replyText"); ?>
            </div>
        <?php endforeach; ?>

        <div class='reply'>
            <?= $form->field($model, 'content') ?>
            <?= $form->field($model, 'A_ID')->hiddenInput(['value' => $item->article_id]) ?>
            <?= Html::submitButton('回覆', ['class' => 'btn btn-primary',]) ?>
        </div>

    </div>
    <?php ActiveForm::end() ?>
<?php endforeach; ?>
<?= LinkPager::widget(['pagination' => $pagination]); ?>

</body>

frontend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A link to reset password will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */

/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

            <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>

            <div class="form-group">
                <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */

/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = '註冊';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>請輸入以下資訊以註冊帳號:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin([
                'id' => 'form-signup',
                'fieldConfig' => [
                    'inputOptions' => ['autocomplete' => 'off'],
                ],
            ]); ?>

            <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

            <?= $form->field($model, 'email') ?>

            <?= $form->field($model, 'password')->passwordInput() ?>

            <div class="form-group">
                <?= Html::submitButton('註冊', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>